defaults: &defaults
  working_directory: ~/app
  docker:
    - image: gradyrogers/awscli

version: 2
jobs: 

  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      # - run:
      #     name: Update CloudFormation
      #     command: |
      #       aws cloudformation update-stack \
      #         --template-body file://cloudformation.yml \
      #         --stack-name cloudfront-archeravenue-distribution \
      #         --parameters ParameterKey=Subdomain,ParameterValue=archeravenue \
      #         --capabilities CAPABILITY_NAMED_IAM \
      #         --region $AWS_REGION
      # - run:
      #     name: Build
      #     command: yarn build:prod
      # - run:
      #     name: Upload
      #     command: |
      #       aws s3 sync dist s3://archeravenuestudio-frontend \
      #         --region $AWS_REGION \
      #         --acl public-read \
      #         --cache-control max-age=300 || echo 'No Updates'

workflows:
  version: 2

  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master